package.json, src/components/OverallMaturityCategoryBreakdown.tsx, src/helpers/maturity_report_helper.js, src/test/OverallMaturityCategoryBreakdown.test.tsx, src/test/OverallMaturityOverview.test.tsx
Some tests required bandaids. Explain why.
=> Clarify ApexCharts Tests and Fix Lint Issues

src/components/EntityOpsLevelMaturityContent.tsx, src/components/Scorecard.tsx, src/test/Scorecard.test.tsx
=> Make scorecard component prettier when using dark theme

src/components/EntityOpsLevelMaturityContent.tsx, src/components/OverallMaturity.tsx, src/components/OverallMaturityCategoryBreakdown.tsx, src/components/OverallMaturityOverview.tsx, src/components/Scorecard.tsx, src/test/OverallMaturityCategoryBreakdown.test.tsx, src/test/OverallMaturityOverview.test.tsx, src/test/Scorecard.test.tsx
=> Make overall maturity charts prettier when using dark theme

src/components/ExportEntitiesForm.tsx, src/components/ExportEntitiesForm/ExportEntitiesForm.tsx, src/components/ExportEntitiesForm/index.ts, src/components/OverallMaturity.tsx
Export Users and Groups to OpsLevel.
=> Export More Entities + Visual Improvements

.eslintrc.js, src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx, src/components/EntityOpsLevelMaturityContent.tsx, src/helpers/level_color_helper.js, src/helpers/maturity_report_helper.js, src/test/CheckResultsByLevel.test.tsx, src/test/Scorecard.test.tsx
=> Fix linter indentation to 2

src/components/Scorecard.tsx, src/test/Scorecard.test.tsx
https://gitlab.com/jklabsinc/OpsLevel/-/issues/7892
=> Replace scorecard level headers with cell tooltips

src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx
No task.
Discussed with Peter; he gave me new color values for the icons to make things look a bit better.
=> Updating icon colors

CHANGELOG.md, src/components/OverallMaturity.tsx, src/images/opslevel-logo.svg
Updates to the [new OpsLevel logo](https://www.opslevel.com/resources/opslevels-new-look) 
Ticket: https://gitlab.com/jklabsinc/opslevel-bs/-/issues/6
<details>
<summary>Different form factors</summary>
</details>
=> Updates to the new logo

CHANGELOG.md, package.json
https://gitlab.com/jklabsinc/OpsLevel/-/issues/9537
=> 1.1.0 release

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/change.yml, .github/pull_request_template.md
- Adds this PR template
- Adds issue templates to allow bug reports and feature requests to be more clear.
[Issue](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/7)
- This is internal process tooling and does not need a changelog.
=> Adds templates for PRs and issues

CHANGELOG.md, README.md, package.json
- Bumps version and changes package name
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/9)
=> Changes package name to a scoped package

.storybook/preview.tsx, src/components/Scorecard.stories.tsx, src/components/Scorecard.tsx
- Adds dark mode support to Storybook
- Switches Scorecard to be a functional component for ease of testing.
[*Please link it here if so*]()
*Please delete this section if it is not relevant*
<details>
<summary>Collapsed Screenshots</summary>
</details
=> Adds dark mode support

CHANGELOG.md, package.json
- add description text to package.json, so the preview text in npm search looks nicer
N/A
=> Add package description text

src/api.ts, src/components/EntityOpsLevelMaturityContent.tsx, src/components/Scorecard.stories.tsx, src/components/Scorecard.tsx, src/components/ServiceMaturitySidebar.stories.tsx, src/components/ServiceMaturitySidebar.tsx, src/test/Scorecard.test.tsx, src/types/OpsLevelData.ts
- Adds scorecards to the sidebar
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/12)
All of this is already in the changelog.
=> Scorecards without filters

CHANGELOG.md, src/api.ts, src/components/CheckResultDetails.stories.tsx, src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx, src/components/EntityOpsLevelMaturityContent.tsx, src/test/CheckResultDetails.test.tsx, src/test/CheckResultsByLevel.test.tsx, src/types/OpsLevelData.ts
- Adds link for Categories along with new styling
- Adds check owner
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/17)
<details>
<summary>Collapsed Screenshots</summary>
</details
=> Check owner and category

CHANGELOG.md, package.json
- Releases new version
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/26)
=> v1.2.1 release

.eslintrc.js, src/components/CheckResultsByLevel.tsx, src/components/EntityOpsLevelMaturityContent.tsx, src/components/ExportEntitiesForm.tsx, src/types/OpsLevelData.ts
- Enables [no-use-before-define](https://eslint.org/docs/latest/rules/no-use-before-define) rule
=> Linting for no-use-before-define

.eslintrc.js, src/components/OverallMaturityCategoryBreakdown.tsx
- Enables [camelcase](https://eslint.org/docs/latest/rules/camelcase) rule
=> Linting: camel case

.eslintrc.js, src/components/MarkdownViewer.tsx, src/components/OverallMaturityCategoryBreakdown.tsx
- Enables [react/sort-comp](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) rule
- Enables [jest/no-conditional-expect](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-conditional-expect.md) rule
=> Lint: no conditional expect and sort-comp

.eslintrc.js, src/components/ExportEntitiesForm.tsx
- Enables [no-await-in-loop](https://eslint.org/docs/latest/rules/no-await-in-loop) rule
=> Linting: no await in loop

.eslintrc.js, src/backend_api.ts
- Enables [no-return-await](https://eslint.org/docs/latest/rules/no-return-await) rule
=> Linting: return await

.eslintrc.js, src/components/MarkdownViewer.tsx, src/components/OverallMaturityCategoryBreakdown.tsx, src/components/OverallMaturityOverview.tsx
- Enables [react/no-access-state-in-setstate](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) rule
=> Linting: react/no-access-state-in-setstate

.eslintrc.js, src/components/CheckResultDetails.tsx, src/components/Scorecard.tsx
- Enables [react/jsx-no-useless-fragment](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md) rule
=> Linting: useless fragment

.eslintrc.js, src/components/MarkdownViewer.tsx
- Enables [react/no-danger](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-danger.md) rule
=> Linting: no danger

.eslintrc.js, src/components/CheckResultDetails.stories.tsx, src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx, src/components/CurrentLevel.tsx, src/components/EntityOpsLevelMaturityContent.tsx, src/components/EntityOpsLevelMaturityProgress.tsx, src/components/OverallMaturity.tsx, src/components/ServiceMaturitySidebar.tsx, src/plugin.ts, src/routes.ts, src/test/CheckResultDetails.test.tsx, src/test/CheckResultsByLevel.test.tsx
- Enables [import/prefer-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md) rule
=> Linting: prefer default export

.github/workflows/release.yaml
- Fixes the `if` statement since I misunderstood how redirects work
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/15)
Not user-facing
=> Bad understanding of redirects in bash

.eslintrc.js, src/components/EntityOpsLevelMaturityContent.tsx
- Enables [no-param-reassign](https://eslint.org/docs/latest/rules/no-param-reassign) rule
=> Linting: no param reassign

.changes/unreleased/Documentation-20231114-084942.yaml, CONTRIBUTING.md
-  Documents release process
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/30)
=> Documents release process

.eslintrc.js, src/components/EntityOpsLevelMaturityContent.tsx, src/components/Scorecard.tsx, src/components/ServiceMaturityError.tsx, src/components/ServiceMaturityReport.tsx, src/components/ServiceMaturitySidebar.stories.tsx, src/components/ServiceMaturitySidebar.tsx, src/test/Scorecard.test.tsx, src/types/OpsLevelData.ts
- Pulls the unstable components out of the top level component
- This is definitely not pretty and there's a lot I'd probably do differently if we started from scratch, but it at least makes these more manageable even if a lot of this stuff could/should be pulled out to hooks and helpers.
Shar
Shared in slack to avoid dumping all of my tabs
=> Last of linting

README.md
Adding a callout to the readme about how authentication solutions can interfere with the proxy.
=> Add note about authentication middleware

.changes/unreleased/Added-20240313-120317.yaml, src/api.ts, src/components/CampaignSummary.tsx, src/components/Campaigns.tsx, src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx, src/components/ColoredCampaignStatus.tsx, src/components/ServiceMaturityReport.tsx, src/test/CampaignSummary.test.tsx, src/test/Campaigns.test.tsx, src/test/CheckResultDetails.test.tsx, src/types/OpsLevelData.ts
- Adds campaigns to the service page
[*Please link it here if so*](https://gitlab.com/jklabsinc/OpsLevel/-/issues/10492)
=> Campaigns on the service page

src/components/BackendExportEntitiesForm.tsx, src/components/CampaignSummary.tsx, src/components/Campaigns.tsx, src/components/CheckResultDetails.tsx, src/components/CheckResultsByLevel.tsx, src/components/ColoredCampaignStatus.tsx, src/components/CurrentLevel.tsx, src/components/EntityOpsLevelMaturityProgress.tsx, src/components/ExportEntitiesForm.tsx, src/components/ScorecardCategory.tsx, src/components/ServiceMaturitySidebar.tsx
- BackstagePlugin doesn't do anything anymore, so we might as well use the more generic term.
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/38)
Not anything user-facing.
=> Remove deprecated theme calls

src/components/Scorecard.tsx, src/components/ScorecardCategory.tsx, src/test/Scorecard.test.tsx
- Fixes header styling
n/a
Updated further styling
=> fix header

.changes/unreleased/Documentation-20240401-162621.yaml, README.md
- Adds documentation for troubleshooting steps we've encountered
[*Please link it here if so*](https://gitlab.com/jklabsinc/OpsLevel/-/issues/10797)
=> Documents troubleshooting steps

.github/workflows/pipeline.yml, .github/workflows/release.yaml
- Switch to node 20 since previous was broken: https://github.com/OpsLevel/backstage-plugin-backend/actions/runs/9067663282
No user impact
=> Bump to node 20 on release

.changes/unreleased/Fixed-20240524-140720.yaml, .github/workflows/pipeline.yml
=> Bumps linting checkout

.github/dependabot.yml
Adds storybook grouping because there are a million bumps for it.
=> Groups storybook dependency upgrades

.changes/unreleased/Added-20240716-133917.yaml, .github/workflows/release.yaml, README.md, package.json
- Note about backstage as internal tool
- Add plugin ID
[*Please link it here if so*](https://gitlab.com/jklabsinc/OpsLevel/-/issues/11619)
=> Fix publishing and add docs

.changes/unreleased/Documentation-20240719-152616.yaml, README.md
- Documents the way to get to the old proxy settings
[*Please link it here if so*](https://gitlab.com/jklabsinc/OpsLevel/-/issues/11627)
=> Documents need for dangerous proxy

.github/dependabot.yml
- Groups dependabots for backstage deps for easier merging
[*Please link it here if so*](https://gitlab.com/jklabsinc/opslevel-bs/-/issues/53)
Just internal
=> Group dependabot for backstage deps

.github/workflows/security.yml
- Adds cron job to scan for security vulnerabilities
[*Please link it here if so*](https://gitlab.com/jklabsinc/OpsLevel/-/issues/11936)
no customer impact
=> Adds grype scan cron job

.changes/unreleased/Fixed-20241211-164220.yaml, src/components/OverallMaturity/BackendExportEntitiesForm.tsx, src/components/OverallMaturity/ExportEntitiesForm.tsx
- Minor style changes around auto sync until we get the Material css working properly
https://gitlab.com/jklabsinc/OpsLevel/-/issues/12526
=> Style tweaks
